### ISSUE TITLE
NameError: global name 'l1l2' is not defined in Model.py

### ISSUE THREAD

**Issue by dhuvik** [eiriniar/CellCnn#2]
Hi eriniar,

I was looking for some help with this error. I have tried running on commandline and ipython yet somehow get caught with this same error. I have tried changing l1l2 to l1_l2 due to a change in the Keras API and modifying model.py to include keras.regularizers.l1_l2 and yet still get the error shown below regardless of the change. Have you encountered such an error? Thanks in advance!

Generating multi-cell inputs...
Done.
Number of filters: 7
Cells pooled: 1
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
.
.
.
NameError: global name 'l1l2' is not defined

**Comment by eiriniar** [comment]
Hello dhuvik, could you please specify which version of Keras you are using? It should be Keras==1.0.4, as indicated in the requirements file.

**Comment by dhuvik** [comment]
Hi Eriniar,

I had 1.0.4 at first and it gave me a Key error stemming from line 480 in model.py:

best_3_nets = [w_store[i] for i in model_sorted_idx]

saying that Key Error:14 (meaning that key wasn't found?) 

I tried fixing this by updating to Keras 1.2 and that's what gave me the l1l2 issue. Any ideas?

Thank you so much for your support! Attached below is the full traceback:

Traceback (most recent call last):
  File "/Users/dxkarthikeyan/cellcnn/CellCnn/cellcnn/run_analysis.py", line 235, in <module>
    main()
  File "/Users/dxkarthikeyan/cellcnn/CellCnn/cellcnn/run_analysis.py", line 178, in main
    outdir=args.outdir)
  File "/Users/dxkarthikeyan/cellcnn/CellCnn/cellCnn/model.py", line 171, in fit
    accur_thres=self.accur_thres, verbose=self.verbose)
  File "/Users/dxkarthikeyan/cellcnn/CellCnn/cellCnn/model.py", line 480, in train_model
    best_3_nets = [w_store[i] for i in model_sorted_idx]
KeyError: 14

**Comment by eiriniar** [comment]
Hello,
Please stick to the version 1.0.4 for Keras, otherwise the code will not be compatible.
Now regarding the key error that you got, that's quite strange. Could you please retry running the run_analysis.py script with the extra argument --nrun 10? Do you still get an error?

**Comment by dhuvik** [comment]
Hi again!

I tried doing the fix you suggested but that just threw the same error and instead of Key error being 14 it was Key Error: 9. When I tried doing --nrun 5 it said Key error 4 and --nrun 4 gave Key Error 3. I tried going over model.py but I'm not sure what could be causing this error. I'll try from another computer but any help on this machine would be super helpful. Thank you again for your patience and support!

**Comment by eiriniar** [comment]
Hello! 
I never had such an error before, so unless I can replicate it, it's difficult to say what's wrong. Do you get this when running the example "python run_analysis.py -f fcs_samples_with_labels.csv -m markers.csv --nrun 3" ? 
And also, do you encounter the same issue from another computer?

**Comment by dhuvik** [comment]
Hi! Ran it from another computer and worked seamlessly! Thank you for your support and patience.
