### ISSUE TITLE
Trouble running the toy example

### ISSUE THREAD

**Issue by henryhuang12345** [eiriniar/CellCnn#3]
Hi May I get some help with going through the tutorial? I am continuously getting the error attached and not sure how to resolve it. Thanks!
<img width="1806" alt="Screen Shot 2020-04-30 at 6 10 35 PM" src="https://user-images.githubusercontent.com/64586132/80699129-10730d80-8b0e-11ea-903a-29e099c00658.png">

**Comment by eiriniar** [comment]
Hi, the issue is that you are currently using Tensorflow. You need to use
Theano as backend for Keras.

**Comment by henryhuang12345** [comment]
Thanks!
