### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by niclas-thomas** [eiriniar/CellCnn#5]
Are there any plans to update the package to support Python 3 now that Python 2 has reached end of life?

**Comment by eiriniar** [comment]
Hi, yes I can do that. It should not require a lot of changes. I'll update
you asap.

**Comment by eiriniar** [comment]
I've created a new branch: https://github.com/eiriniar/CellCnn/tree/python3
with a Python 3.7 implementation. 
Please let me know if you try it out and encounter any issues.

**Comment by niclas-thomas** [comment]
Great thanks, will have a look soon
